# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            huesler-informatik
tagline:          'My 2 cents'
description:      'Working with computers'
url:              http://www.huesler-informatik.ch
baseurl:          '/'
paginate:         5

author:
  name:           'Patrick Huesler'
  url:            https://twitter.com/phuesler

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
