# Dependencies
markdown:         redcarpet
highlighter:      pygments

plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            huesler.io
tagline:          'My 2 cents'
description:      'A blog written by Patrick Huesler'
url:              http://www.huesler.io
baseurl:          '/'
paginate:         5

author:
  name:           'Patrick Huesler'
  url:            https://twitter.com/phuesler

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
