task default: %w[build]

task :release => [:build, :deploy]

task :deploy do
  exec 'rsync -avz _site/ mosphere@server23.hostpoint.ch:/home/mosphere/www/huesler-informatik.ch/'
end

task :build do
  exec 'jekyll build'
end

task :server do
  exec 'jekyll server --drafts --watch'
end
